// This file was auto-generated by Fern from our API Definition.

import { ExecClient } from "./api/resources/exec/client/Client.js";
import { FilesClient } from "./api/resources/files/client/Client.js";
import { SandboxesClient } from "./api/resources/sandboxes/client/Client.js";
import { SystemClient } from "./api/resources/system/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";
import * as environments from "./environments.js";

export declare namespace SuperserveClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SuperserveClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SuperserveClient.Options>;
    protected _system: SystemClient | undefined;
    protected _sandboxes: SandboxesClient | undefined;
    protected _exec: ExecClient | undefined;
    protected _files: FilesClient | undefined;

    constructor(options: SuperserveClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get system(): SystemClient {
        return (this._system ??= new SystemClient(this._options));
    }

    public get sandboxes(): SandboxesClient {
        return (this._sandboxes ??= new SandboxesClient(this._options));
    }

    public get exec(): ExecClient {
        return (this._exec ??= new ExecClient(this._options));
    }

    public get files(): FilesClient {
        return (this._files ??= new FilesClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl:
                    this._options.baseUrl ??
                    (async () => {
                        const env = await core.Supplier.get(this._options.environment);
                        return typeof env === "string"
                            ? env
                            : ((env as Record<string, string>)?.base ??
                                  environments.SuperserveEnvironment.Production.base);
                    }),
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
