// This file was auto-generated by Fern from our API Definition.

export const SuperserveEnvironment = {
    Production: "https://api.superserve.ai",
} as const;

export type SuperserveEnvironment = typeof SuperserveEnvironment.Production;
