# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawFilesClient, RawFilesClient
from .types.upload_file_response import UploadFileResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FilesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFilesClient
        """
        return self._raw_client

    def download_file(
        self, sandbox_id: str, path: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Idle sandboxes are automatically resumed before the download.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        path : str
            File path inside the sandbox (without leading slash).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            File content

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.files.download_file(
            sandbox_id="sandbox_id",
            path="path",
        )
        """
        with self._raw_client.download_file(sandbox_id, path, request_options=request_options) as r:
            yield from r.data

    def upload_file(
        self,
        sandbox_id: str,
        path: str,
        *,
        request: typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadFileResponse:
        """
        Idle sandboxes are automatically resumed before the upload.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        path : str
            File path inside the sandbox (without leading slash).

        request : typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadFileResponse
            File uploaded
        """
        _response = self._raw_client.upload_file(sandbox_id, path, request=request, request_options=request_options)
        return _response.data


class AsyncFilesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFilesClient
        """
        return self._raw_client

    async def download_file(
        self, sandbox_id: str, path: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Idle sandboxes are automatically resumed before the download.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        path : str
            File path inside the sandbox (without leading slash).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            File content

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.download_file(
                sandbox_id="sandbox_id",
                path="path",
            )


        asyncio.run(main())
        """
        async with self._raw_client.download_file(sandbox_id, path, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk

    async def upload_file(
        self,
        sandbox_id: str,
        path: str,
        *,
        request: typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadFileResponse:
        """
        Idle sandboxes are automatically resumed before the upload.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        path : str
            File path inside the sandbox (without leading slash).

        request : typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadFileResponse
            File uploaded
        """
        _response = await self._raw_client.upload_file(
            sandbox_id, path, request=request, request_options=request_options
        )
        return _response.data
