// This file was auto-generated by Fern from our API Definition.

import type * as Superserve from "../../../../index.js";

/**
 * @example
 *     {
 *         sandbox_id: "sandbox_id",
 *         body: {
 *             command: "command"
 *         }
 *     }
 */
export interface ExecCommandRequest {
    /** The unique identifier of the sandbox. */
    sandbox_id: string;
    body: Superserve.ExecRequest;
}
