// This file was auto-generated by Fern from our API Definition.

export interface Error_ {
    error?: Error_.Error_ | undefined;
}

export namespace Error_ {
    export interface Error_ {
        code?: string | undefined;
        message?: string | undefined;
    }
}
