// This file was auto-generated by Fern from our API Definition.

export interface ExecResult {
    stdout?: string | undefined;
    stderr?: string | undefined;
    exit_code?: number | undefined;
}
