// This file was auto-generated by Fern from our API Definition.

/**
 * A single SSE event payload emitted by the exec/stream endpoint.
 */
export interface ExecStreamEvent {
    timestamp?: string | undefined;
    /** Stdout chunk (present when the process wrote to stdout). */
    stdout?: string | undefined;
    /** Stderr chunk (present when the process wrote to stderr). */
    stderr?: string | undefined;
    /** Process exit code (present on the final event). */
    exit_code?: number | undefined;
    /** True on the final event. */
    finished?: boolean | undefined;
    /** Error message if the exec itself failed (present on the final event on error). */
    error?: string | undefined;
}
