// This file was auto-generated by Fern from our API Definition.

export interface ExecRequest {
    /** Command to execute. Wrapped in `/bin/sh -c` unless `args` is provided. */
    command: string;
    /** If provided, `command` is used as the binary and `args` as arguments (no shell wrapping). */
    args?: string[] | undefined;
    /** Environment variables for the command. */
    env?: Record<string, string> | undefined;
    /** Working directory (default /home/user). */
    working_dir?: string | undefined;
    /** Timeout in seconds. */
    timeout_s?: number | undefined;
}
