// This file was auto-generated by Fern from our API Definition.

/**
 * Egress network rules for a sandbox. `allow_out` accepts CIDRs (e.g. `8.8.8.8/32`) and domain names (e.g. `api.openai.com`, `*.github.com`). `deny_out` accepts CIDRs only. Private ranges (10/8, 172.16/12, 192.168/16, 127/8, 169.254/16) are always blocked regardless of rules.
 */
export interface NetworkConfig {
    /** CIDRs or domains to allow. */
    allow_out?: string[] | undefined;
    /** CIDRs to deny. Use `0.0.0.0/0` to block all traffic not in `allow_out`. */
    deny_out?: string[] | undefined;
}
