// This file was auto-generated by Fern from our API Definition.

export interface SandboxResponse {
    id?: string | undefined;
    name?: string | undefined;
    status?: SandboxResponse.Status | undefined;
    vcpu_count?: number | undefined;
    memory_mib?: number | undefined;
    /** IP address of the running VM (present when status is active). */
    ip_address?: string | undefined;
    /** ID of the latest snapshot (present after a pause). */
    snapshot_id?: string | undefined;
    created_at?: string | undefined;
}

export namespace SandboxResponse {
    export const Status = {
        Starting: "starting",
        Active: "active",
        Pausing: "pausing",
        Idle: "idle",
        Deleted: "deleted",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
