// This file was auto-generated by Fern from our API Definition.

import type * as Superserve from "../index.js";

export interface SandboxResponse {
    id?: string | undefined;
    name?: string | undefined;
    status?: SandboxResponse.Status | undefined;
    vcpu_count?: number | undefined;
    memory_mib?: number | undefined;
    /**
     * Per-sandbox HMAC access token for data-plane operations
     * (file upload/download, terminal). Pass as `X-Access-Token`
     * header when hitting the edge proxy at
     * `boxd-{id}.sandbox.superserve.ai`. Reusable for the
     * lifetime of the sandbox.
     */
    access_token?: string | undefined;
    /** ID of the latest snapshot (present after a pause). */
    snapshot_id?: string | undefined;
    created_at?: string | undefined;
    /** Hard lifetime cap in seconds from creation, if set at creation time. Absent when no cap was configured. */
    timeout_seconds?: number | undefined;
    /** Current egress allow/deny rules, if any have been configured. Absent when the sandbox uses default network settings. */
    network?: Superserve.NetworkConfig | undefined;
    /** User-supplied tags attached at creation. Always present — sandboxes created without metadata return `{}` rather than being absent. */
    metadata?: Record<string, string> | undefined;
}

export namespace SandboxResponse {
    export const Status = {
        Starting: "starting",
        Active: "active",
        Pausing: "pausing",
        Idle: "idle",
        Deleted: "deleted",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
