# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ExecRequest(UniversalBaseModel):
    command: str = pydantic.Field()
    """
    Command to execute. Wrapped in `/bin/sh -c` unless `args` is provided.
    """

    args: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    If provided, `command` is used as the binary and `args` as arguments (no shell wrapping).
    """

    env: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Environment variables for the command.
    """

    working_dir: typing.Optional[str] = pydantic.Field(default=None)
    """
    Working directory (default /home/user).
    """

    timeout_s: typing.Optional[int] = pydantic.Field(default=None)
    """
    Timeout in seconds.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
