# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ExecStreamEvent(UniversalBaseModel):
    """
    A single SSE event payload emitted by the exec/stream endpoint.
    """

    timestamp: typing.Optional[dt.datetime] = None
    stdout: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stdout chunk (present when the process wrote to stdout).
    """

    stderr: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stderr chunk (present when the process wrote to stderr).
    """

    exit_code: typing.Optional[int] = pydantic.Field(default=None)
    """
    Process exit code (present on the final event).
    """

    finished: typing.Optional[bool] = pydantic.Field(default=None)
    """
    True on the final event.
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error message if the exec itself failed (present on the final event on error).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
