# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class NetworkConfig(UniversalBaseModel):
    """
    Egress network rules for a sandbox. `allow_out` accepts CIDRs (e.g. `8.8.8.8/32`) and domain names (e.g. `api.openai.com`, `*.github.com`). `deny_out` accepts CIDRs only. Private ranges (10/8, 172.16/12, 192.168/16, 127/8, 169.254/16) are always blocked regardless of rules.
    """

    allow_out: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    CIDRs or domains to allow.
    """

    deny_out: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    CIDRs to deny. Use `0.0.0.0/0` to block all traffic not in `allow_out`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
