# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .sandbox_response_status import SandboxResponseStatus


class SandboxResponse(UniversalBaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    status: typing.Optional[SandboxResponseStatus] = None
    vcpu_count: typing.Optional[int] = None
    memory_mib: typing.Optional[int] = None
    ip_address: typing.Optional[str] = pydantic.Field(default=None)
    """
    IP address of the running VM (present when status is active).
    """

    snapshot_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the latest snapshot (present after a pause).
    """

    created_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
