// This file was auto-generated by Fern from our API Definition.

import type * as Superserve from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface CreateSandboxRequest {
    /** Human-readable name for the sandbox. */
    name: string;
    /** If provided, boot the sandbox from this snapshot instead of creating a fresh VM. The snapshot must belong to the same team. */
    from_snapshot?: string;
    network?: Superserve.NetworkConfig;
}
