// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sandbox_id: "sandbox_id"
 *     }
 */
export interface DeleteSandboxRequest {
    /** The unique identifier of the sandbox. */
    sandbox_id: string;
}
