// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListSandboxesRequest {
    /**
     * Filter sandboxes whose metadata contains an exact `{key}: <value>`
     * pair. Repeat with different keys to AND multiple filters. Values
     * are always strings. Example: `?metadata.env=prod`.
     */
    "metadata.{key}"?: string;
}
