// This file was auto-generated by Fern from our API Definition.

import type * as Superserve from "../../../../index.js";

/**
 * @example
 *     {
 *         sandbox_id: "sandbox_id",
 *         network: {
 *             allow_out: ["api.openai.com", "*.github.com"],
 *             deny_out: ["0.0.0.0/0"]
 *         }
 *     }
 */
export interface SandboxPatch {
    /** The unique identifier of the sandbox. */
    sandbox_id: string;
    /**
     * Replace the sandbox's egress rules. The sandbox must be in
     * the `active` state. The provided `allow_out` and `deny_out`
     * lists fully replace whatever was previously configured.
     */
    network?: Superserve.NetworkConfig;
}
