// This file was auto-generated by Fern from our API Definition.

import type * as Superserve from "../../../../index.js";

/**
 * @example
 *     {
 *         sandbox_id: "sandbox_id",
 *         metadata: {
 *             "env": "prod",
 *             "owner": "agent-7"
 *         }
 *     }
 */
export interface SandboxPatch {
    /** The unique identifier of the sandbox. */
    sandbox_id: string;
    /**
     * Replace the sandbox's egress rules. The sandbox must be in
     * the `active` state. The provided `allow_out` and `deny_out`
     * lists fully replace whatever was previously configured.
     */
    network?: Superserve.NetworkConfig;
    /**
     * Replace the sandbox's metadata tags. Fully replaces the existing
     * metadata — omitted keys are removed. Can be patched regardless of
     * sandbox state. Same validation limits as on create (64 keys,
     * 256-byte keys, 2 KB values, 16 KB total).
     */
    metadata?: Record<string, string>;
}
