# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.exec_result import ExecResult
from ..types.exec_stream_event import ExecStreamEvent
from .raw_client import AsyncRawExecClient, RawExecClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ExecClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawExecClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawExecClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawExecClient
        """
        return self._raw_client

    def command(
        self,
        sandbox_id: str,
        *,
        command: str,
        args: typing.Optional[typing.Sequence[str]] = OMIT,
        env: typing.Optional[typing.Dict[str, str]] = OMIT,
        working_dir: typing.Optional[str] = OMIT,
        timeout_s: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExecResult:
        """
        Runs a command inside the sandbox and waits for it to finish, returning
        stdout, stderr, and exit code. Idle sandboxes are automatically resumed
        before execution.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        command : str
            Command to execute. Wrapped in `/bin/sh -c` unless `args` is provided.

        args : typing.Optional[typing.Sequence[str]]
            If provided, `command` is used as the binary and `args` as arguments (no shell wrapping).

        env : typing.Optional[typing.Dict[str, str]]
            Environment variables for the command.

        working_dir : typing.Optional[str]
            Working directory (default /home/user).

        timeout_s : typing.Optional[int]
            Timeout in seconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExecResult
            Command executed

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.exec.command(
            sandbox_id="sandbox_id",
            command="command",
        )
        """
        _response = self._raw_client.command(
            sandbox_id,
            command=command,
            args=args,
            env=env,
            working_dir=working_dir,
            timeout_s=timeout_s,
            request_options=request_options,
        )
        return _response.data

    def command_stream(
        self,
        sandbox_id: str,
        *,
        command: str,
        args: typing.Optional[typing.Sequence[str]] = OMIT,
        env: typing.Optional[typing.Dict[str, str]] = OMIT,
        working_dir: typing.Optional[str] = OMIT,
        timeout_s: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[ExecStreamEvent]:
        """
        Runs a command and streams stdout/stderr chunks as Server-Sent Events.
        Each event is a JSON payload. The final event includes `exit_code` and
        `finished: true`. Idle sandboxes are automatically resumed before execution.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        command : str
            Command to execute. Wrapped in `/bin/sh -c` unless `args` is provided.

        args : typing.Optional[typing.Sequence[str]]
            If provided, `command` is used as the binary and `args` as arguments (no shell wrapping).

        env : typing.Optional[typing.Dict[str, str]]
            Environment variables for the command.

        working_dir : typing.Optional[str]
            Working directory (default /home/user).

        timeout_s : typing.Optional[int]
            Timeout in seconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[ExecStreamEvent]
            SSE stream. Each line starting with `data: ` contains a JSON `ExecStreamEvent`. The final event has `finished: true`.

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        response = client.exec.command_stream(
            sandbox_id="sandbox_id",
            command="command",
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.command_stream(
            sandbox_id,
            command=command,
            args=args,
            env=env,
            working_dir=working_dir,
            timeout_s=timeout_s,
            request_options=request_options,
        ) as r:
            yield from r.data


class AsyncExecClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawExecClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawExecClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawExecClient
        """
        return self._raw_client

    async def command(
        self,
        sandbox_id: str,
        *,
        command: str,
        args: typing.Optional[typing.Sequence[str]] = OMIT,
        env: typing.Optional[typing.Dict[str, str]] = OMIT,
        working_dir: typing.Optional[str] = OMIT,
        timeout_s: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ExecResult:
        """
        Runs a command inside the sandbox and waits for it to finish, returning
        stdout, stderr, and exit code. Idle sandboxes are automatically resumed
        before execution.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        command : str
            Command to execute. Wrapped in `/bin/sh -c` unless `args` is provided.

        args : typing.Optional[typing.Sequence[str]]
            If provided, `command` is used as the binary and `args` as arguments (no shell wrapping).

        env : typing.Optional[typing.Dict[str, str]]
            Environment variables for the command.

        working_dir : typing.Optional[str]
            Working directory (default /home/user).

        timeout_s : typing.Optional[int]
            Timeout in seconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ExecResult
            Command executed

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.exec.command(
                sandbox_id="sandbox_id",
                command="command",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.command(
            sandbox_id,
            command=command,
            args=args,
            env=env,
            working_dir=working_dir,
            timeout_s=timeout_s,
            request_options=request_options,
        )
        return _response.data

    async def command_stream(
        self,
        sandbox_id: str,
        *,
        command: str,
        args: typing.Optional[typing.Sequence[str]] = OMIT,
        env: typing.Optional[typing.Dict[str, str]] = OMIT,
        working_dir: typing.Optional[str] = OMIT,
        timeout_s: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[ExecStreamEvent]:
        """
        Runs a command and streams stdout/stderr chunks as Server-Sent Events.
        Each event is a JSON payload. The final event includes `exit_code` and
        `finished: true`. Idle sandboxes are automatically resumed before execution.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        command : str
            Command to execute. Wrapped in `/bin/sh -c` unless `args` is provided.

        args : typing.Optional[typing.Sequence[str]]
            If provided, `command` is used as the binary and `args` as arguments (no shell wrapping).

        env : typing.Optional[typing.Dict[str, str]]
            Environment variables for the command.

        working_dir : typing.Optional[str]
            Working directory (default /home/user).

        timeout_s : typing.Optional[int]
            Timeout in seconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[ExecStreamEvent]
            SSE stream. Each line starting with `data: ` contains a JSON `ExecStreamEvent`. The final event has `finished: true`.

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.exec.command_stream(
                sandbox_id="sandbox_id",
                command="command",
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.command_stream(
            sandbox_id,
            command=command,
            args=args,
            env=env,
            working_dir=working_dir,
            timeout_s=timeout_s,
            request_options=request_options,
        ) as r:
            async for _chunk in r.data:
                yield _chunk
