# This file was auto-generated by Fern from our API Definition.

import contextlib
import typing
from json.decoder import JSONDecodeError
from logging import error, warning

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.http_sse._api import EventSource
from ..core.jsonable_encoder import jsonable_encoder
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as, parse_sse_obj
from ..core.request_options import RequestOptions
from ..errors.conflict_error import ConflictError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.error import Error
from ..types.exec_result import ExecResult
from ..types.exec_stream_event import ExecStreamEvent
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawExecClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def command(
        self,
        sandbox_id: str,
        *,
        command: str,
        args: typing.Optional[typing.Sequence[str]] = OMIT,
        env: typing.Optional[typing.Dict[str, str]] = OMIT,
        working_dir: typing.Optional[str] = OMIT,
        timeout_s: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ExecResult]:
        """
        Runs a command inside the sandbox and waits for it to finish, returning
        stdout, stderr, and exit code. Idle sandboxes are automatically resumed
        before execution.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        command : str
            Command to execute. Wrapped in `/bin/sh -c` unless `args` is provided.

        args : typing.Optional[typing.Sequence[str]]
            If provided, `command` is used as the binary and `args` as arguments (no shell wrapping).

        env : typing.Optional[typing.Dict[str, str]]
            Environment variables for the command.

        working_dir : typing.Optional[str]
            Working directory (default /home/user).

        timeout_s : typing.Optional[int]
            Timeout in seconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ExecResult]
            Command executed
        """
        _response = self._client_wrapper.httpx_client.request(
            f"sandboxes/{jsonable_encoder(sandbox_id)}/exec",
            method="POST",
            json={
                "command": command,
                "args": args,
                "env": env,
                "working_dir": working_dir,
                "timeout_s": timeout_s,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExecResult,
                    parse_obj_as(
                        type_=ExecResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    @contextlib.contextmanager
    def command_stream(
        self,
        sandbox_id: str,
        *,
        command: str,
        args: typing.Optional[typing.Sequence[str]] = OMIT,
        env: typing.Optional[typing.Dict[str, str]] = OMIT,
        working_dir: typing.Optional[str] = OMIT,
        timeout_s: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[HttpResponse[typing.Iterator[ExecStreamEvent]]]:
        """
        Runs a command and streams stdout/stderr chunks as Server-Sent Events.
        Each event is a JSON payload. The final event includes `exit_code` and
        `finished: true`. Idle sandboxes are automatically resumed before execution.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        command : str
            Command to execute. Wrapped in `/bin/sh -c` unless `args` is provided.

        args : typing.Optional[typing.Sequence[str]]
            If provided, `command` is used as the binary and `args` as arguments (no shell wrapping).

        env : typing.Optional[typing.Dict[str, str]]
            Environment variables for the command.

        working_dir : typing.Optional[str]
            Working directory (default /home/user).

        timeout_s : typing.Optional[int]
            Timeout in seconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[HttpResponse[typing.Iterator[ExecStreamEvent]]]
            SSE stream. Each line starting with `data: ` contains a JSON `ExecStreamEvent`. The final event has `finished: true`.
        """
        with self._client_wrapper.httpx_client.stream(
            f"sandboxes/{jsonable_encoder(sandbox_id)}/exec/stream",
            method="POST",
            json={
                "command": command,
                "args": args,
                "env": env,
                "working_dir": working_dir,
                "timeout_s": timeout_s,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        ) as _response:

            def _stream() -> HttpResponse[typing.Iterator[ExecStreamEvent]]:
                try:
                    if 200 <= _response.status_code < 300:

                        def _iter():
                            _event_source = EventSource(_response)
                            for _sse in _event_source.iter_sse():
                                if _sse.data == None:
                                    return
                                try:
                                    yield typing.cast(
                                        ExecStreamEvent,
                                        parse_sse_obj(
                                            sse=_sse,
                                            type_=ExecStreamEvent,  # type: ignore
                                        ),
                                    )
                                except JSONDecodeError as e:
                                    warning(f"Skipping SSE event with invalid JSON: {e}, sse: {_sse!r}")
                                except (TypeError, ValueError, KeyError, AttributeError) as e:
                                    warning(
                                        f"Skipping SSE event due to model construction error: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                                except Exception as e:
                                    error(
                                        f"Unexpected error processing SSE event: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                            return

                        return HttpResponse(response=_response, data=_iter())
                    _response.read()
                    if _response.status_code == 401:
                        raise UnauthorizedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                Error,
                                parse_obj_as(
                                    type_=Error,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 404:
                        raise NotFoundError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                Error,
                                parse_obj_as(
                                    type_=Error,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 409:
                        raise ConflictError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                Error,
                                parse_obj_as(
                                    type_=Error,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 500:
                        raise InternalServerError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                Error,
                                parse_obj_as(
                                    type_=Error,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                except ValidationError as e:
                    raise ParsingError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.json(),
                        cause=e,
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield _stream()


class AsyncRawExecClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def command(
        self,
        sandbox_id: str,
        *,
        command: str,
        args: typing.Optional[typing.Sequence[str]] = OMIT,
        env: typing.Optional[typing.Dict[str, str]] = OMIT,
        working_dir: typing.Optional[str] = OMIT,
        timeout_s: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ExecResult]:
        """
        Runs a command inside the sandbox and waits for it to finish, returning
        stdout, stderr, and exit code. Idle sandboxes are automatically resumed
        before execution.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        command : str
            Command to execute. Wrapped in `/bin/sh -c` unless `args` is provided.

        args : typing.Optional[typing.Sequence[str]]
            If provided, `command` is used as the binary and `args` as arguments (no shell wrapping).

        env : typing.Optional[typing.Dict[str, str]]
            Environment variables for the command.

        working_dir : typing.Optional[str]
            Working directory (default /home/user).

        timeout_s : typing.Optional[int]
            Timeout in seconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ExecResult]
            Command executed
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"sandboxes/{jsonable_encoder(sandbox_id)}/exec",
            method="POST",
            json={
                "command": command,
                "args": args,
                "env": env,
                "working_dir": working_dir,
                "timeout_s": timeout_s,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ExecResult,
                    parse_obj_as(
                        type_=ExecResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        Error,
                        parse_obj_as(
                            type_=Error,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    @contextlib.asynccontextmanager
    async def command_stream(
        self,
        sandbox_id: str,
        *,
        command: str,
        args: typing.Optional[typing.Sequence[str]] = OMIT,
        env: typing.Optional[typing.Dict[str, str]] = OMIT,
        working_dir: typing.Optional[str] = OMIT,
        timeout_s: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[ExecStreamEvent]]]:
        """
        Runs a command and streams stdout/stderr chunks as Server-Sent Events.
        Each event is a JSON payload. The final event includes `exit_code` and
        `finished: true`. Idle sandboxes are automatically resumed before execution.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        command : str
            Command to execute. Wrapped in `/bin/sh -c` unless `args` is provided.

        args : typing.Optional[typing.Sequence[str]]
            If provided, `command` is used as the binary and `args` as arguments (no shell wrapping).

        env : typing.Optional[typing.Dict[str, str]]
            Environment variables for the command.

        working_dir : typing.Optional[str]
            Working directory (default /home/user).

        timeout_s : typing.Optional[int]
            Timeout in seconds.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[ExecStreamEvent]]]
            SSE stream. Each line starting with `data: ` contains a JSON `ExecStreamEvent`. The final event has `finished: true`.
        """
        async with self._client_wrapper.httpx_client.stream(
            f"sandboxes/{jsonable_encoder(sandbox_id)}/exec/stream",
            method="POST",
            json={
                "command": command,
                "args": args,
                "env": env,
                "working_dir": working_dir,
                "timeout_s": timeout_s,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        ) as _response:

            async def _stream() -> AsyncHttpResponse[typing.AsyncIterator[ExecStreamEvent]]:
                try:
                    if 200 <= _response.status_code < 300:

                        async def _iter():
                            _event_source = EventSource(_response)
                            async for _sse in _event_source.aiter_sse():
                                if _sse.data == None:
                                    return
                                try:
                                    yield typing.cast(
                                        ExecStreamEvent,
                                        parse_sse_obj(
                                            sse=_sse,
                                            type_=ExecStreamEvent,  # type: ignore
                                        ),
                                    )
                                except JSONDecodeError as e:
                                    warning(f"Skipping SSE event with invalid JSON: {e}, sse: {_sse!r}")
                                except (TypeError, ValueError, KeyError, AttributeError) as e:
                                    warning(
                                        f"Skipping SSE event due to model construction error: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                                except Exception as e:
                                    error(
                                        f"Unexpected error processing SSE event: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                            return

                        return AsyncHttpResponse(response=_response, data=_iter())
                    await _response.aread()
                    if _response.status_code == 401:
                        raise UnauthorizedError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                Error,
                                parse_obj_as(
                                    type_=Error,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 404:
                        raise NotFoundError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                Error,
                                parse_obj_as(
                                    type_=Error,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 409:
                        raise ConflictError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                Error,
                                parse_obj_as(
                                    type_=Error,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    if _response.status_code == 500:
                        raise InternalServerError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                Error,
                                parse_obj_as(
                                    type_=Error,  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                except ValidationError as e:
                    raise ParsingError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.json(),
                        cause=e,
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield await _stream()
