# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.network_config import NetworkConfig
from ..types.sandbox_response import SandboxResponse
from .raw_client import AsyncRawSandboxesClient, RawSandboxesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SandboxesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSandboxesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSandboxesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSandboxesClient
        """
        return self._raw_client

    def list_sandboxes(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SandboxResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SandboxResponse]
            List of sandboxes belonging to the authenticated team

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.list_sandboxes()
        """
        _response = self._raw_client.list_sandboxes(request_options=request_options)
        return _response.data

    def create_sandbox(
        self,
        *,
        name: str,
        from_snapshot: typing.Optional[str] = OMIT,
        network: typing.Optional[NetworkConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SandboxResponse:
        """
        Creates a sandbox and returns immediately with `status: starting`.
        The VM boots asynchronously. Poll `GET /sandboxes/{id}` until
        `status` is `active` before running commands.

        Parameters
        ----------
        name : str
            Human-readable name for the sandbox.

        from_snapshot : typing.Optional[str]
            If provided, boot the sandbox from this snapshot instead of creating a fresh VM. The snapshot must belong to the same team.

        network : typing.Optional[NetworkConfig]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox created

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.create_sandbox(
            name="name",
        )
        """
        _response = self._raw_client.create_sandbox(
            name=name, from_snapshot=from_snapshot, network=network, request_options=request_options
        )
        return _response.data

    def get_sandbox(
        self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SandboxResponse:
        """
        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox details

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.get_sandbox(
            sandbox_id="sandbox_id",
        )
        """
        _response = self._raw_client.get_sandbox(sandbox_id, request_options=request_options)
        return _response.data

    def delete_sandbox(self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.delete_sandbox(
            sandbox_id="sandbox_id",
        )
        """
        _response = self._raw_client.delete_sandbox(sandbox_id, request_options=request_options)
        return _response.data

    def patch_sandbox(
        self,
        sandbox_id: str,
        *,
        network: typing.Optional[NetworkConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Applies a partial update to a running sandbox. Each top-level field
        in the request body is optional; only fields that are present are
        applied. Omitted top-level fields are left unchanged. Nested objects
        are full replacements when present — to clear a list, send it as an
        empty array.

        At least one top-level field must be present, otherwise the request
        is rejected with `400`. Unknown top-level fields are also rejected
        with `400` so typos surface as errors instead of silent no-ops.

        ## Currently patchable fields

        - `network` — replaces the egress allow/deny rules. The sandbox
          must be in the `active` state; patching a paused or idle sandbox
          returns `409`. Rules take effect immediately and are persisted so
          they survive a future pause/resume cycle.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        network : typing.Optional[NetworkConfig]
            Replace the sandbox's egress rules. The sandbox must be in
            the `active` state. The provided `allow_out` and `deny_out`
            lists fully replace whatever was previously configured.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from superserve import NetworkConfig, Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.patch_sandbox(
            sandbox_id="sandbox_id",
            network=NetworkConfig(
                allow_out=["api.openai.com", "*.github.com"],
                deny_out=["0.0.0.0/0"],
            ),
        )
        """
        _response = self._raw_client.patch_sandbox(sandbox_id, network=network, request_options=request_options)
        return _response.data

    def pause_sandbox(
        self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SandboxResponse:
        """
        Snapshots the sandbox's full state (memory + disk), suspends the VM,
        and transitions to `idle`. Resume it later to continue exactly where
        it left off.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox is now idle

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.pause_sandbox(
            sandbox_id="sandbox_id",
        )
        """
        _response = self._raw_client.pause_sandbox(sandbox_id, request_options=request_options)
        return _response.data

    def resume_sandbox(
        self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SandboxResponse:
        """
        Restores the sandbox from its paused snapshot. Transitions back to
        `active` with all state intact — same memory, same processes, same files.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox is now active

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.resume_sandbox(
            sandbox_id="sandbox_id",
        )
        """
        _response = self._raw_client.resume_sandbox(sandbox_id, request_options=request_options)
        return _response.data


class AsyncSandboxesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSandboxesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSandboxesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSandboxesClient
        """
        return self._raw_client

    async def list_sandboxes(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SandboxResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SandboxResponse]
            List of sandboxes belonging to the authenticated team

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.list_sandboxes()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_sandboxes(request_options=request_options)
        return _response.data

    async def create_sandbox(
        self,
        *,
        name: str,
        from_snapshot: typing.Optional[str] = OMIT,
        network: typing.Optional[NetworkConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SandboxResponse:
        """
        Creates a sandbox and returns immediately with `status: starting`.
        The VM boots asynchronously. Poll `GET /sandboxes/{id}` until
        `status` is `active` before running commands.

        Parameters
        ----------
        name : str
            Human-readable name for the sandbox.

        from_snapshot : typing.Optional[str]
            If provided, boot the sandbox from this snapshot instead of creating a fresh VM. The snapshot must belong to the same team.

        network : typing.Optional[NetworkConfig]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox created

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.create_sandbox(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_sandbox(
            name=name, from_snapshot=from_snapshot, network=network, request_options=request_options
        )
        return _response.data

    async def get_sandbox(
        self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SandboxResponse:
        """
        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox details

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.get_sandbox(
                sandbox_id="sandbox_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_sandbox(sandbox_id, request_options=request_options)
        return _response.data

    async def delete_sandbox(self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.delete_sandbox(
                sandbox_id="sandbox_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_sandbox(sandbox_id, request_options=request_options)
        return _response.data

    async def patch_sandbox(
        self,
        sandbox_id: str,
        *,
        network: typing.Optional[NetworkConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Applies a partial update to a running sandbox. Each top-level field
        in the request body is optional; only fields that are present are
        applied. Omitted top-level fields are left unchanged. Nested objects
        are full replacements when present — to clear a list, send it as an
        empty array.

        At least one top-level field must be present, otherwise the request
        is rejected with `400`. Unknown top-level fields are also rejected
        with `400` so typos surface as errors instead of silent no-ops.

        ## Currently patchable fields

        - `network` — replaces the egress allow/deny rules. The sandbox
          must be in the `active` state; patching a paused or idle sandbox
          returns `409`. Rules take effect immediately and are persisted so
          they survive a future pause/resume cycle.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        network : typing.Optional[NetworkConfig]
            Replace the sandbox's egress rules. The sandbox must be in
            the `active` state. The provided `allow_out` and `deny_out`
            lists fully replace whatever was previously configured.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve, NetworkConfig

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.patch_sandbox(
                sandbox_id="sandbox_id",
                network=NetworkConfig(
                    allow_out=["api.openai.com", "*.github.com"],
                    deny_out=["0.0.0.0/0"],
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.patch_sandbox(sandbox_id, network=network, request_options=request_options)
        return _response.data

    async def pause_sandbox(
        self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SandboxResponse:
        """
        Snapshots the sandbox's full state (memory + disk), suspends the VM,
        and transitions to `idle`. Resume it later to continue exactly where
        it left off.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox is now idle

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.pause_sandbox(
                sandbox_id="sandbox_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.pause_sandbox(sandbox_id, request_options=request_options)
        return _response.data

    async def resume_sandbox(
        self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SandboxResponse:
        """
        Restores the sandbox from its paused snapshot. Transitions back to
        `active` with all state intact — same memory, same processes, same files.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox is now active

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.resume_sandbox(
                sandbox_id="sandbox_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resume_sandbox(sandbox_id, request_options=request_options)
        return _response.data
