# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.network_config import NetworkConfig
from ..types.sandbox_response import SandboxResponse
from .raw_client import AsyncRawSandboxesClient, RawSandboxesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SandboxesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSandboxesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSandboxesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSandboxesClient
        """
        return self._raw_client

    def list_sandboxes(
        self, *, metadata_key: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SandboxResponse]:
        """
        Returns sandboxes belonging to the authenticated team, optionally
        filtered by metadata tags.

        ## Filtering by metadata

        Any query parameter prefixed `metadata.` is treated as a filter
        clause: `?metadata.env=prod&metadata.owner=agent-7`. Multiple
        filters AND together — a sandbox matches only if every key/value
        pair is present in its metadata. Values are compared as exact
        strings; there is no type coercion or substring matching.

        Parameters
        ----------
        metadata_key : typing.Optional[str]
            Filter sandboxes whose metadata contains an exact `{key}: <value>`
            pair. Repeat with different keys to AND multiple filters. Values
            are always strings. Example: `?metadata.env=prod`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SandboxResponse]
            List of sandboxes belonging to the authenticated team

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.list_sandboxes()
        """
        _response = self._raw_client.list_sandboxes(metadata_key=metadata_key, request_options=request_options)
        return _response.data

    def create_sandbox(
        self,
        *,
        name: str,
        from_snapshot: typing.Optional[str] = OMIT,
        timeout_seconds: typing.Optional[int] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        env_vars: typing.Optional[typing.Dict[str, str]] = OMIT,
        network: typing.Optional[NetworkConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SandboxResponse:
        """
        Creates a sandbox and returns immediately with `status: starting`.
        The VM boots asynchronously. Poll `GET /sandboxes/{id}` until
        `status` is `active` before running commands.

        Parameters
        ----------
        name : str
            Human-readable name for the sandbox.

        from_snapshot : typing.Optional[str]
            If provided, boot the sandbox from this snapshot instead of creating a fresh VM. The snapshot must belong to the same team.

        timeout_seconds : typing.Optional[int]
            Optional hard lifetime cap in seconds, measured from sandbox creation. When set, the sandbox is destroyed this many seconds after creation regardless of state (active, paused, idle) or activity — the user asked for a hard deadline. When unset, the sandbox lives until explicitly paused or deleted. Maximum 604800 (7 days).

        metadata : typing.Optional[typing.Dict[str, str]]
            Flat string-to-string tags attached to the sandbox at creation.
            Useful for grouping, owner labels, environment, run IDs, etc.

            ## Constraints
              - **Strings only.** Values must be strings. There is no type
                coercion: `metadata.count=42` filters for the *string* "42".
              - **At most 64 keys.**
              - Each key may be at most **256 bytes**.
              - Each value may be at most **2048 bytes** (2 KB).
              - The serialized object may be at most **16384 bytes** (16 KB)
                in total.
              - Keys starting with `superserve.` or `_superserve` (case-
                insensitive) are reserved for platform use and rejected.

            Metadata can be updated after creation via `PATCH /sandboxes/:id`.
            Filter sandboxes by metadata via the `metadata.{key}` query
            parameter on `GET /sandboxes`.

        env_vars : typing.Optional[typing.Dict[str, str]]
            Environment variables injected into every process inside the
            sandbox (terminal sessions, exec calls). Not persisted in the
            database — they live in the VM agent's memory for the sandbox's
            lifetime and survive pause/resume via snapshot.

        network : typing.Optional[NetworkConfig]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox created

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.create_sandbox(
            name="name",
        )
        """
        _response = self._raw_client.create_sandbox(
            name=name,
            from_snapshot=from_snapshot,
            timeout_seconds=timeout_seconds,
            metadata=metadata,
            env_vars=env_vars,
            network=network,
            request_options=request_options,
        )
        return _response.data

    def get_sandbox(
        self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SandboxResponse:
        """
        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox details

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.get_sandbox(
            sandbox_id="sandbox_id",
        )
        """
        _response = self._raw_client.get_sandbox(sandbox_id, request_options=request_options)
        return _response.data

    def delete_sandbox(self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.delete_sandbox(
            sandbox_id="sandbox_id",
        )
        """
        _response = self._raw_client.delete_sandbox(sandbox_id, request_options=request_options)
        return _response.data

    def patch_sandbox(
        self,
        sandbox_id: str,
        *,
        network: typing.Optional[NetworkConfig] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Applies a partial update to a running sandbox. Each top-level field
        in the request body is optional; only fields that are present are
        applied. Omitted top-level fields are left unchanged. Nested objects
        are full replacements when present — to clear a list, send it as an
        empty array.

        At least one top-level field must be present, otherwise the request
        is rejected with `400`. Unknown top-level fields are also rejected
        with `400` so typos surface as errors instead of silent no-ops.

        ## Currently patchable fields

        - `network` — replaces the egress allow/deny rules. The sandbox
          must be in the `active` state; patching a paused or idle sandbox
          returns `409`. Rules take effect immediately and are persisted so
          they survive a future pause/resume cycle.
        - `metadata` — replaces the sandbox's metadata tags. Can be updated
          regardless of sandbox state (active, paused, idle).

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        network : typing.Optional[NetworkConfig]
            Replace the sandbox's egress rules. The sandbox must be in
            the `active` state. The provided `allow_out` and `deny_out`
            lists fully replace whatever was previously configured.

        metadata : typing.Optional[typing.Dict[str, str]]
            Replace the sandbox's metadata tags. Fully replaces the existing
            metadata — omitted keys are removed. Can be patched regardless of
            sandbox state. Same validation limits as on create (64 keys,
            256-byte keys, 2 KB values, 16 KB total).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.patch_sandbox(
            sandbox_id="sandbox_id",
            metadata={"env": "prod", "owner": "agent-7"},
        )
        """
        _response = self._raw_client.patch_sandbox(
            sandbox_id, network=network, metadata=metadata, request_options=request_options
        )
        return _response.data

    def pause_sandbox(
        self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SandboxResponse:
        """
        Snapshots the sandbox's full state (memory + disk), suspends the VM,
        and transitions to `idle`. Resume it later to continue exactly where
        it left off.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox is now idle

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.pause_sandbox(
            sandbox_id="sandbox_id",
        )
        """
        _response = self._raw_client.pause_sandbox(sandbox_id, request_options=request_options)
        return _response.data

    def resume_sandbox(
        self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SandboxResponse:
        """
        Restores the sandbox from its paused snapshot. Transitions back to
        `active` with all state intact — same memory, same processes, same files.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox is now active

        Examples
        --------
        from superserve import Superserve

        client = Superserve(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.resume_sandbox(
            sandbox_id="sandbox_id",
        )
        """
        _response = self._raw_client.resume_sandbox(sandbox_id, request_options=request_options)
        return _response.data


class AsyncSandboxesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSandboxesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSandboxesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSandboxesClient
        """
        return self._raw_client

    async def list_sandboxes(
        self, *, metadata_key: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[SandboxResponse]:
        """
        Returns sandboxes belonging to the authenticated team, optionally
        filtered by metadata tags.

        ## Filtering by metadata

        Any query parameter prefixed `metadata.` is treated as a filter
        clause: `?metadata.env=prod&metadata.owner=agent-7`. Multiple
        filters AND together — a sandbox matches only if every key/value
        pair is present in its metadata. Values are compared as exact
        strings; there is no type coercion or substring matching.

        Parameters
        ----------
        metadata_key : typing.Optional[str]
            Filter sandboxes whose metadata contains an exact `{key}: <value>`
            pair. Repeat with different keys to AND multiple filters. Values
            are always strings. Example: `?metadata.env=prod`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[SandboxResponse]
            List of sandboxes belonging to the authenticated team

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.list_sandboxes()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_sandboxes(metadata_key=metadata_key, request_options=request_options)
        return _response.data

    async def create_sandbox(
        self,
        *,
        name: str,
        from_snapshot: typing.Optional[str] = OMIT,
        timeout_seconds: typing.Optional[int] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        env_vars: typing.Optional[typing.Dict[str, str]] = OMIT,
        network: typing.Optional[NetworkConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SandboxResponse:
        """
        Creates a sandbox and returns immediately with `status: starting`.
        The VM boots asynchronously. Poll `GET /sandboxes/{id}` until
        `status` is `active` before running commands.

        Parameters
        ----------
        name : str
            Human-readable name for the sandbox.

        from_snapshot : typing.Optional[str]
            If provided, boot the sandbox from this snapshot instead of creating a fresh VM. The snapshot must belong to the same team.

        timeout_seconds : typing.Optional[int]
            Optional hard lifetime cap in seconds, measured from sandbox creation. When set, the sandbox is destroyed this many seconds after creation regardless of state (active, paused, idle) or activity — the user asked for a hard deadline. When unset, the sandbox lives until explicitly paused or deleted. Maximum 604800 (7 days).

        metadata : typing.Optional[typing.Dict[str, str]]
            Flat string-to-string tags attached to the sandbox at creation.
            Useful for grouping, owner labels, environment, run IDs, etc.

            ## Constraints
              - **Strings only.** Values must be strings. There is no type
                coercion: `metadata.count=42` filters for the *string* "42".
              - **At most 64 keys.**
              - Each key may be at most **256 bytes**.
              - Each value may be at most **2048 bytes** (2 KB).
              - The serialized object may be at most **16384 bytes** (16 KB)
                in total.
              - Keys starting with `superserve.` or `_superserve` (case-
                insensitive) are reserved for platform use and rejected.

            Metadata can be updated after creation via `PATCH /sandboxes/:id`.
            Filter sandboxes by metadata via the `metadata.{key}` query
            parameter on `GET /sandboxes`.

        env_vars : typing.Optional[typing.Dict[str, str]]
            Environment variables injected into every process inside the
            sandbox (terminal sessions, exec calls). Not persisted in the
            database — they live in the VM agent's memory for the sandbox's
            lifetime and survive pause/resume via snapshot.

        network : typing.Optional[NetworkConfig]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox created

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.create_sandbox(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_sandbox(
            name=name,
            from_snapshot=from_snapshot,
            timeout_seconds=timeout_seconds,
            metadata=metadata,
            env_vars=env_vars,
            network=network,
            request_options=request_options,
        )
        return _response.data

    async def get_sandbox(
        self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SandboxResponse:
        """
        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox details

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.get_sandbox(
                sandbox_id="sandbox_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_sandbox(sandbox_id, request_options=request_options)
        return _response.data

    async def delete_sandbox(self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.delete_sandbox(
                sandbox_id="sandbox_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_sandbox(sandbox_id, request_options=request_options)
        return _response.data

    async def patch_sandbox(
        self,
        sandbox_id: str,
        *,
        network: typing.Optional[NetworkConfig] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Applies a partial update to a running sandbox. Each top-level field
        in the request body is optional; only fields that are present are
        applied. Omitted top-level fields are left unchanged. Nested objects
        are full replacements when present — to clear a list, send it as an
        empty array.

        At least one top-level field must be present, otherwise the request
        is rejected with `400`. Unknown top-level fields are also rejected
        with `400` so typos surface as errors instead of silent no-ops.

        ## Currently patchable fields

        - `network` — replaces the egress allow/deny rules. The sandbox
          must be in the `active` state; patching a paused or idle sandbox
          returns `409`. Rules take effect immediately and are persisted so
          they survive a future pause/resume cycle.
        - `metadata` — replaces the sandbox's metadata tags. Can be updated
          regardless of sandbox state (active, paused, idle).

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        network : typing.Optional[NetworkConfig]
            Replace the sandbox's egress rules. The sandbox must be in
            the `active` state. The provided `allow_out` and `deny_out`
            lists fully replace whatever was previously configured.

        metadata : typing.Optional[typing.Dict[str, str]]
            Replace the sandbox's metadata tags. Fully replaces the existing
            metadata — omitted keys are removed. Can be patched regardless of
            sandbox state. Same validation limits as on create (64 keys,
            256-byte keys, 2 KB values, 16 KB total).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.patch_sandbox(
                sandbox_id="sandbox_id",
                metadata={"env": "prod", "owner": "agent-7"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.patch_sandbox(
            sandbox_id, network=network, metadata=metadata, request_options=request_options
        )
        return _response.data

    async def pause_sandbox(
        self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SandboxResponse:
        """
        Snapshots the sandbox's full state (memory + disk), suspends the VM,
        and transitions to `idle`. Resume it later to continue exactly where
        it left off.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox is now idle

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.pause_sandbox(
                sandbox_id="sandbox_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.pause_sandbox(sandbox_id, request_options=request_options)
        return _response.data

    async def resume_sandbox(
        self, sandbox_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SandboxResponse:
        """
        Restores the sandbox from its paused snapshot. Transitions back to
        `active` with all state intact — same memory, same processes, same files.

        Parameters
        ----------
        sandbox_id : str
            The unique identifier of the sandbox.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxResponse
            Sandbox is now active

        Examples
        --------
        import asyncio

        from superserve import AsyncSuperserve

        client = AsyncSuperserve(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.resume_sandbox(
                sandbox_id="sandbox_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resume_sandbox(sandbox_id, request_options=request_options)
        return _response.data
