// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Superserve from "../../../index.js";

export declare namespace SandboxesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SandboxesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SandboxesClient.Options>;

    constructor(options: SandboxesClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns sandboxes belonging to the authenticated team, optionally
     * filtered by metadata tags.
     *
     * ## Filtering by metadata
     *
     * Any query parameter prefixed `metadata.` is treated as a filter
     * clause: `?metadata.env=prod&metadata.owner=agent-7`. Multiple
     * filters AND together — a sandbox matches only if every key/value
     * pair is present in its metadata. Values are compared as exact
     * strings; there is no type coercion or substring matching.
     *
     * @param {Superserve.ListSandboxesRequest} request
     * @param {SandboxesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Superserve.BadRequestError}
     * @throws {@link Superserve.UnauthorizedError}
     * @throws {@link Superserve.InternalServerError}
     *
     * @example
     *     await client.sandboxes.listSandboxes()
     */
    public listSandboxes(
        request: Superserve.ListSandboxesRequest = {},
        requestOptions?: SandboxesClient.RequestOptions,
    ): core.HttpResponsePromise<Superserve.SandboxResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__listSandboxes(request, requestOptions));
    }

    private async __listSandboxes(
        request: Superserve.ListSandboxesRequest = {},
        requestOptions?: SandboxesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Superserve.SandboxResponse[]>> {
        const { "metadata.{key}": metadataKey } = request;
        const _queryParams: Record<string, unknown> = {
            "metadata.{key}": metadataKey,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.SuperserveEnvironment.Production
                    ).base,
                "sandboxes",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Superserve.SandboxResponse[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Superserve.BadRequestError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Superserve.UnauthorizedError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Superserve.InternalServerError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SuperserveError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/sandboxes");
    }

    /**
     * Creates a sandbox and returns immediately with `status: starting`.
     * The VM boots asynchronously. Poll `GET /sandboxes/{id}` until
     * `status` is `active` before running commands.
     *
     * @param {Superserve.CreateSandboxRequest} request
     * @param {SandboxesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Superserve.BadRequestError}
     * @throws {@link Superserve.UnauthorizedError}
     * @throws {@link Superserve.InternalServerError}
     *
     * @example
     *     await client.sandboxes.createSandbox({
     *         name: "name"
     *     })
     */
    public createSandbox(
        request: Superserve.CreateSandboxRequest,
        requestOptions?: SandboxesClient.RequestOptions,
    ): core.HttpResponsePromise<Superserve.SandboxResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createSandbox(request, requestOptions));
    }

    private async __createSandbox(
        request: Superserve.CreateSandboxRequest,
        requestOptions?: SandboxesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Superserve.SandboxResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.SuperserveEnvironment.Production
                    ).base,
                "sandboxes",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Superserve.SandboxResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Superserve.BadRequestError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Superserve.UnauthorizedError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Superserve.InternalServerError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SuperserveError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/sandboxes");
    }

    /**
     * @param {Superserve.GetSandboxRequest} request
     * @param {SandboxesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Superserve.UnauthorizedError}
     * @throws {@link Superserve.NotFoundError}
     * @throws {@link Superserve.InternalServerError}
     *
     * @example
     *     await client.sandboxes.getSandbox({
     *         sandbox_id: "sandbox_id"
     *     })
     */
    public getSandbox(
        request: Superserve.GetSandboxRequest,
        requestOptions?: SandboxesClient.RequestOptions,
    ): core.HttpResponsePromise<Superserve.SandboxResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getSandbox(request, requestOptions));
    }

    private async __getSandbox(
        request: Superserve.GetSandboxRequest,
        requestOptions?: SandboxesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Superserve.SandboxResponse>> {
        const { sandbox_id: sandboxId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.SuperserveEnvironment.Production
                    ).base,
                `sandboxes/${core.url.encodePathParam(sandboxId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Superserve.SandboxResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Superserve.UnauthorizedError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Superserve.NotFoundError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Superserve.InternalServerError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SuperserveError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/sandboxes/{sandbox_id}");
    }

    /**
     * @param {Superserve.DeleteSandboxRequest} request
     * @param {SandboxesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Superserve.UnauthorizedError}
     * @throws {@link Superserve.NotFoundError}
     * @throws {@link Superserve.InternalServerError}
     *
     * @example
     *     await client.sandboxes.deleteSandbox({
     *         sandbox_id: "sandbox_id"
     *     })
     */
    public deleteSandbox(
        request: Superserve.DeleteSandboxRequest,
        requestOptions?: SandboxesClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteSandbox(request, requestOptions));
    }

    private async __deleteSandbox(
        request: Superserve.DeleteSandboxRequest,
        requestOptions?: SandboxesClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { sandbox_id: sandboxId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.SuperserveEnvironment.Production
                    ).base,
                `sandboxes/${core.url.encodePathParam(sandboxId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Superserve.UnauthorizedError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Superserve.NotFoundError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Superserve.InternalServerError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SuperserveError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/sandboxes/{sandbox_id}");
    }

    /**
     * Applies a partial update to a running sandbox. Each top-level field
     * in the request body is optional; only fields that are present are
     * applied. Omitted top-level fields are left unchanged. Nested objects
     * are full replacements when present — to clear a list, send it as an
     * empty array.
     *
     * At least one top-level field must be present, otherwise the request
     * is rejected with `400`. Unknown top-level fields are also rejected
     * with `400` so typos surface as errors instead of silent no-ops.
     *
     * ## Currently patchable fields
     *
     * - `network` — replaces the egress allow/deny rules. The sandbox
     *   must be in the `active` state; patching a paused or idle sandbox
     *   returns `409`. Rules take effect immediately and are persisted so
     *   they survive a future pause/resume cycle.
     * - `metadata` — replaces the sandbox's metadata tags. Can be updated
     *   regardless of sandbox state (active, paused, idle).
     *
     * @param {Superserve.SandboxPatch} request
     * @param {SandboxesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Superserve.BadRequestError}
     * @throws {@link Superserve.UnauthorizedError}
     * @throws {@link Superserve.NotFoundError}
     * @throws {@link Superserve.ConflictError}
     * @throws {@link Superserve.InternalServerError}
     *
     * @example
     *     await client.sandboxes.patchSandbox({
     *         sandbox_id: "sandbox_id",
     *         metadata: {
     *             "env": "prod",
     *             "owner": "agent-7"
     *         }
     *     })
     */
    public patchSandbox(
        request: Superserve.SandboxPatch,
        requestOptions?: SandboxesClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__patchSandbox(request, requestOptions));
    }

    private async __patchSandbox(
        request: Superserve.SandboxPatch,
        requestOptions?: SandboxesClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { sandbox_id: sandboxId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.SuperserveEnvironment.Production
                    ).base,
                `sandboxes/${core.url.encodePathParam(sandboxId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Superserve.BadRequestError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Superserve.UnauthorizedError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Superserve.NotFoundError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 409:
                    throw new Superserve.ConflictError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Superserve.InternalServerError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SuperserveError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/sandboxes/{sandbox_id}");
    }

    /**
     * Snapshots the sandbox's full state (memory + disk), suspends the VM,
     * and transitions to `idle`. Resume it later to continue exactly where
     * it left off.
     *
     * @param {Superserve.PauseSandboxRequest} request
     * @param {SandboxesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Superserve.UnauthorizedError}
     * @throws {@link Superserve.NotFoundError}
     * @throws {@link Superserve.ConflictError}
     * @throws {@link Superserve.InternalServerError}
     *
     * @example
     *     await client.sandboxes.pauseSandbox({
     *         sandbox_id: "sandbox_id"
     *     })
     */
    public pauseSandbox(
        request: Superserve.PauseSandboxRequest,
        requestOptions?: SandboxesClient.RequestOptions,
    ): core.HttpResponsePromise<Superserve.SandboxResponse> {
        return core.HttpResponsePromise.fromPromise(this.__pauseSandbox(request, requestOptions));
    }

    private async __pauseSandbox(
        request: Superserve.PauseSandboxRequest,
        requestOptions?: SandboxesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Superserve.SandboxResponse>> {
        const { sandbox_id: sandboxId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.SuperserveEnvironment.Production
                    ).base,
                `sandboxes/${core.url.encodePathParam(sandboxId)}/pause`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Superserve.SandboxResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Superserve.UnauthorizedError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Superserve.NotFoundError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 409:
                    throw new Superserve.ConflictError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Superserve.InternalServerError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SuperserveError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/sandboxes/{sandbox_id}/pause",
        );
    }

    /**
     * Restores the sandbox from its paused snapshot. Transitions back to
     * `active` with all state intact — same memory, same processes, same files.
     *
     * @param {Superserve.ResumeSandboxRequest} request
     * @param {SandboxesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Superserve.UnauthorizedError}
     * @throws {@link Superserve.NotFoundError}
     * @throws {@link Superserve.ConflictError}
     * @throws {@link Superserve.InternalServerError}
     *
     * @example
     *     await client.sandboxes.resumeSandbox({
     *         sandbox_id: "sandbox_id"
     *     })
     */
    public resumeSandbox(
        request: Superserve.ResumeSandboxRequest,
        requestOptions?: SandboxesClient.RequestOptions,
    ): core.HttpResponsePromise<Superserve.SandboxResponse> {
        return core.HttpResponsePromise.fromPromise(this.__resumeSandbox(request, requestOptions));
    }

    private async __resumeSandbox(
        request: Superserve.ResumeSandboxRequest,
        requestOptions?: SandboxesClient.RequestOptions,
    ): Promise<core.WithRawResponse<Superserve.SandboxResponse>> {
        const { sandbox_id: sandboxId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (
                        (await core.Supplier.get(this._options.environment)) ??
                        environments.SuperserveEnvironment.Production
                    ).base,
                `sandboxes/${core.url.encodePathParam(sandboxId)}/resume`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Superserve.SandboxResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Superserve.UnauthorizedError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Superserve.NotFoundError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 409:
                    throw new Superserve.ConflictError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Superserve.InternalServerError(
                        _response.error.body as Superserve.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SuperserveError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/sandboxes/{sandbox_id}/resume",
        );
    }
}
