# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        Error,
        ErrorError,
        ExecRequest,
        ExecResult,
        ExecStreamEvent,
        NetworkConfig,
        SandboxResponse,
        SandboxResponseStatus,
    )
    from .errors import BadRequestError, ConflictError, InternalServerError, NotFoundError, UnauthorizedError
    from . import exec, sandboxes, system
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import AsyncSuperserve, Superserve
    from .environment import SuperserveEnvironment
    from .system import HealthResponse
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncSuperserve": ".client",
    "BadRequestError": ".errors",
    "ConflictError": ".errors",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "Error": ".types",
    "ErrorError": ".types",
    "ExecRequest": ".types",
    "ExecResult": ".types",
    "ExecStreamEvent": ".types",
    "HealthResponse": ".system",
    "InternalServerError": ".errors",
    "NetworkConfig": ".types",
    "NotFoundError": ".errors",
    "SandboxResponse": ".types",
    "SandboxResponseStatus": ".types",
    "Superserve": ".client",
    "SuperserveEnvironment": ".environment",
    "UnauthorizedError": ".errors",
    "exec": ".exec",
    "sandboxes": ".sandboxes",
    "system": ".system",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncSuperserve",
    "BadRequestError",
    "ConflictError",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "Error",
    "ErrorError",
    "ExecRequest",
    "ExecResult",
    "ExecStreamEvent",
    "HealthResponse",
    "InternalServerError",
    "NetworkConfig",
    "NotFoundError",
    "SandboxResponse",
    "SandboxResponseStatus",
    "Superserve",
    "SuperserveEnvironment",
    "UnauthorizedError",
    "exec",
    "sandboxes",
    "system",
]
