# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .environment import SuperserveEnvironment

if typing.TYPE_CHECKING:
    from .exec.client import AsyncExecClient, ExecClient
    from .files.client import AsyncFilesClient, FilesClient
    from .sandboxes.client import AsyncSandboxesClient, SandboxesClient
    from .system.client import AsyncSystemClient, SystemClient


class Superserve:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    environment : SuperserveEnvironment
        The environment to use for requests from the client. from .environment import SuperserveEnvironment



        Defaults to SuperserveEnvironment.PRODUCTION



    sandbox_id : typing.Optional[str]
        Server URL variable for 'sandbox_id'. Defaults to ''.

    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from superserve import Superserve

    client = Superserve(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        environment: SuperserveEnvironment = SuperserveEnvironment.PRODUCTION,
        sandbox_id: typing.Optional[str] = None,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        if sandbox_id is not None:
            _sandbox_id = sandbox_id if sandbox_id is not None else ""
            environment = SuperserveEnvironment(
                base="https://api.superserve.ai",
                sandbox_data_plane="https://boxd-{sandbox_id}.sandbox.superserve.ai".format(sandbox_id=_sandbox_id),
            )
        self._client_wrapper = SyncClientWrapper(
            environment=environment,
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._system: typing.Optional[SystemClient] = None
        self._sandboxes: typing.Optional[SandboxesClient] = None
        self._exec: typing.Optional[ExecClient] = None
        self._files: typing.Optional[FilesClient] = None

    @property
    def system(self):
        if self._system is None:
            from .system.client import SystemClient  # noqa: E402

            self._system = SystemClient(client_wrapper=self._client_wrapper)
        return self._system

    @property
    def sandboxes(self):
        if self._sandboxes is None:
            from .sandboxes.client import SandboxesClient  # noqa: E402

            self._sandboxes = SandboxesClient(client_wrapper=self._client_wrapper)
        return self._sandboxes

    @property
    def exec(self):
        if self._exec is None:
            from .exec.client import ExecClient  # noqa: E402

            self._exec = ExecClient(client_wrapper=self._client_wrapper)
        return self._exec

    @property
    def files(self):
        if self._files is None:
            from .files.client import FilesClient  # noqa: E402

            self._files = FilesClient(client_wrapper=self._client_wrapper)
        return self._files


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncSuperserve:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    environment : SuperserveEnvironment
        The environment to use for requests from the client. from .environment import SuperserveEnvironment



        Defaults to SuperserveEnvironment.PRODUCTION



    sandbox_id : typing.Optional[str]
        Server URL variable for 'sandbox_id'. Defaults to ''.

    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from superserve import AsyncSuperserve

    client = AsyncSuperserve(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        environment: SuperserveEnvironment = SuperserveEnvironment.PRODUCTION,
        sandbox_id: typing.Optional[str] = None,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        if sandbox_id is not None:
            _sandbox_id = sandbox_id if sandbox_id is not None else ""
            environment = SuperserveEnvironment(
                base="https://api.superserve.ai",
                sandbox_data_plane="https://boxd-{sandbox_id}.sandbox.superserve.ai".format(sandbox_id=_sandbox_id),
            )
        self._client_wrapper = AsyncClientWrapper(
            environment=environment,
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._system: typing.Optional[AsyncSystemClient] = None
        self._sandboxes: typing.Optional[AsyncSandboxesClient] = None
        self._exec: typing.Optional[AsyncExecClient] = None
        self._files: typing.Optional[AsyncFilesClient] = None

    @property
    def system(self):
        if self._system is None:
            from .system.client import AsyncSystemClient  # noqa: E402

            self._system = AsyncSystemClient(client_wrapper=self._client_wrapper)
        return self._system

    @property
    def sandboxes(self):
        if self._sandboxes is None:
            from .sandboxes.client import AsyncSandboxesClient  # noqa: E402

            self._sandboxes = AsyncSandboxesClient(client_wrapper=self._client_wrapper)
        return self._sandboxes

    @property
    def exec(self):
        if self._exec is None:
            from .exec.client import AsyncExecClient  # noqa: E402

            self._exec = AsyncExecClient(client_wrapper=self._client_wrapper)
        return self._exec

    @property
    def files(self):
        if self._files is None:
            from .files.client import AsyncFilesClient  # noqa: E402

            self._files = AsyncFilesClient(client_wrapper=self._client_wrapper)
        return self._files
