# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations


class SuperserveEnvironment:
    PRODUCTION: SuperserveEnvironment

    def __init__(self, *, base: str, sandbox_data_plane: str):
        self.base = base
        self.sandbox_data_plane = sandbox_data_plane


SuperserveEnvironment.PRODUCTION = SuperserveEnvironment(
    base="https://api.superserve.ai", sandbox_data_plane="https://boxd.sandbox.superserve.ai"
)
