// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "X-Access-Token": "accessToken",
 *         path: "path"
 *     }
 */
export interface DownloadFileRequest {
    /**
     * Absolute file path inside the sandbox. Must start with `/` and
     * must not contain `..` segments.
     */
    path: string;
    /**
     * Per-sandbox HMAC access token. Take this from
     * `SandboxResponse.access_token` on the sandbox you're reading from.
     */
    "X-Access-Token": string;
}
