// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sandbox_id: "sandbox_id",
 *         path: "path"
 *     }
 */
export interface DownloadFileRequest {
    /** The unique identifier of the sandbox. */
    sandbox_id: string;
    /** File path inside the sandbox (without leading slash). */
    path: string;
}
