// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         path: "/home/user/data.txt"
 *     }
 */
export interface UploadFileRequest {
    /**
     * Absolute destination path inside the sandbox. Must start with `/`
     * and must not contain `..` segments.
     */
    path: string;
}
